---
- name: Instalando Apache
  ansible.builtin.dnf:
    name: httpd
    state: latest

- name: Iniciar o servico e habilitar no boot
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: Copiando Index
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html
    owner: apache
    group: apache
    mode: '0644'
  notify:
    - restart httpd

- name: Verificando firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: libera trafego http
  ansible.posix.firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled