---
- name: Instalando DHCP Server
  ansible.builtin.dnf:
    name: dhcpd-server
    state: latest

- name: Iniciar o servico e habilitar no boot
  ansible.builtin.service:
    name: dhcpd
    state: started
    enabled: yes

- name: libera dhcp
  ansible.posix.firewalld:
    service: dhcp
    permanent: true
    immediate: true
    state: enabled

- name: lendo csv
  community.general.read_csv:
    path: files/hosts.csv
  register: hosts
  delegate_to: localhost

- name: Criando o arquivo dhcp.conf
  ansible.builtin.template:
    src: templates/dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf