---
- name: Instalando DHCP Server
  ansible.builtin.dnf:
    name: dhcpd-server
    state: latest

- name: Iniciar o servico e habilitar no boot
  ansible.builtin.service:
    name: dhcpd
    state: started
    enabled: yes

- name: libera dhcp
  ansible.posix.firewalld:
    service: dhcp
    permanent: true
    immediate: true
    state: enabled